### PR TITLE
use OverlayNGRobust 

### PR DESCRIPTION
**Pull request by neil-cse**
* use OverlayNGRobust for union/intersection/difference, 
* add coercion options to their interfaces, 
* if they fail, try making the inputs valid and trying again

What do you think of the new interfaces?

### CODE REVIEW

**Review by larkery — APPROVED** [review]
This looks good to me. Two thoughts:

1. When we do operations with a desired output type, should we validate them (the outputs) as well? And/or filter out invalid? On the one hand it gives us the semantic of "intersect these polygons to a set of valid polygons" etc which is what we often want to say. On the other hand, it will have overhead and might be too much forcing (if it hides some legit error)
2. Might be good to put in a test like "union two multilinestrings to line strings" which includes things like intersection to a point as well as a line etc. I'm pretty sure it works from reading it but maybe deserves a test

**Comment by larkery** [comment]
Something to consider is whether we make-valid on the outputs of functions, or inputs to functions, or both.

At the moment we're doing that to inputs in the `catch` block. I think 

I feel like maybe always doing make-valid on the outputs, and throwing if we can't produce a valid output so we die ASAP might be the thing.

The only question that remains is whether we ever want to allow invalid stuff but then just discard it because it's probably chaff.

**Comment by neil-cse** [comment]
I think always making the outputs valid is a good thing to do. 

I'm not sure about filtering out invalid things - they can nearly always be made valid, and then if they're the wrong type they'll get filtered out anyway, and if they're the right type we might want them.

I think generally make-valid succeeds, or (rarely) throws (I've never seen it happen I don't think) - it's failure mode is generally 'the newly-valid output looks nothing like the input' more than 'the output is still invalid'.

**Comment by neil-cse** [comment]
One other thing - I guess it'd be nice to be able to coerce the output of the 1-arity `union`. I was thinking of splitting it out into a separate `unary-union` function or something. Sound ok?

**Comment by larkery** [comment]
Ah good point. I think there are two options:

```clj
;; either
(defn union ([x] ...) ([x y] ..)) 
(defn union-as [x output] ...)

;; or

(defn union 
   ([x] unary)
   ([x y-or-output] (if (keyword? y-or-output) unary binary))
   ([x y output] binary))
```

Not sure which I find more upsetting right now.

It's a shame clojure's design doesn't allow variadic + keyword args or it could just be `:as :polygons` etc.

**Comment by larkery** [comment]
Do you think we should make-valid after buffer as well, since that's made wrong results in the past?

**Comment by neil-cse** [comment]
I think https://github.com/cse-bristol/clj-geometry/pull/4/commits/85529e8fc104b5e00c1e55a432abbb0818e40ce5 is less weird

> Do you think we should make-valid after buffer as well, since that's made wrong results in the past?

Mmm yes maybe...

**Comment by neil-cse** [comment]
> Also makes me think: do we want to be able to say 'as some polygons' vs 'as a single multipolygon' etc by this argument? Or do we leave that for chaining to g/make-multipolygon?

You can do both of these, `:polygons` vs `:multi-polygon`

**Comment by neil-cse** [comment]
> Or one other option which is to expose the coerce function and wrap everything at the call site, so
> 
> (-> (g/union a b) (g/as :polygon))
> 
> instead of
> (g/union a b :polygon)

Maybe this is the better approach. Certainly fits the style of all the other JTS/geos libs, none of who have overlay options that allow this sort of thing

**Comment by larkery** [comment]
I didn't interpret `coerce` properly first time, my bad.

I feel chaining functions rather than magic argument is the right thing here, having given it more consideration. It doesn't make the calling code much longer to write and it's a bit clearer.

**Comment by neil-cse** [comment]
Agreed, will change

**Comment by larkery** [comment]
Not sure what the name for `coerce` should be. I'm tempted by `as` or `to` but maybe `coerce` makes it a bit clearer we're doing something potentially fishy.

I guess we're leaving `make-valid` inside all the operations though, since the contract is something like "I want to union these things to a valid geometry" and then "I want to get whatever polygons I can out of this valid geometry"

**Comment by neil-cse** [comment]
> Not sure what the name for coerce should be. I'm tempted by as or to but maybe coerce makes it a bit clearer we're doing something potentially fishy.

I liked `as`, too. Though the tricky thing here is what to do about features. `as` and `as-of` doesn't work.

> I guess we're leaving make-valid inside all the operations though, since the contract is something like "I want to union these things to a valid geometry" and then "I want to get whatever polygons I can out of this valid geometry"

Yes, that was my plan. You have to make-valid first, in case it changes the type of a thing

**Comment by neil-cse** [comment]
I think I've convinced myself we don't really need an `as` at all, and think what we currently do (call `polygons-of`, or `polygons` if we want to keep a Feature) is probably nicer, if anything. It's more flexible, as it gives the choice between Feature and not-Feature.

**Pull request merged**
